In [1]:
import numpy as np

matrix = np.matrix('6 -11 6; 1 0 0; 0 1 0')

# Berechne die Eigenwerte von matrix
eigenwerte, einheitsEVs = np.linalg.eig(matrix)

print("Eigenwerte:", eigenwerte)
print("Einheits-Eigenvektoren:")
print(einheitsEVs)

Eigenwerte: [3. 2. 1.]
Einheits-Eigenvektoren:
[[0.94345635 0.87287156 0.57735027]
 [0.31448545 0.43643578 0.57735027]
 [0.10482848 0.21821789 0.57735027]]
